// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:286afe27-5240-4a1b-a826-d1de52198582",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_J3y8Ay8OR",
    "aws_user_pools_web_client_id": "5c96fqfkogue031isee9mqifvb",
    "oauth": {},
    "aws_mobile_analytics_app_id": "aa31dbff6c974f59bedab4d4faf1cf85",
    "aws_mobile_analytics_app_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://2n55cgz23bgvzk7osregxsm2he.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
